spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: sa
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

